version: "3"
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - /tmp/db:/var/lib/postgresql/data
    web:
        build: .
        command: bundle exec rails server -p 3000 -b 0.0.0.0
        environment:
            DB_HOST: db
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
        volumes:
            - .:/application
        ports:
            - 3000:3000
        depends_on:
            - db